# Generated by Django 4.2.1 on 2023-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
